/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.demo.kafka.json.consumer.dto;

import com.demo.kafka.json.consumer.constants.MessageType;
import com.fasterxml.jackson.annotation.JsonProperty;

public class MessageValue {


    @JsonProperty
    private String productId;
    @JsonProperty
    private String name;
    @JsonProperty
    private int rating;
    @JsonProperty
    private String comment;

    @JsonProperty
    private MessageType messageType;

    public MessageValue() {
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public MessageType getMessageType() {
        return messageType;
    }

    public void setMessageType(MessageType messageType) {
        this.messageType = messageType;
    }

    public MessageValue(String productId, String name, int rating, String comment, MessageType messageType) {
        this.productId = productId;
        this.name = name;
        this.rating = rating;
        this.comment = comment;
        this.messageType=messageType;
    }

    @Override
    public String toString() {
        return "MessageValue{" +
                "productId='" + productId + '\'' +
                ", name='" + name + '\'' +
                ", rating=" + rating +
                ", comment='" + comment + '\'' +
                ", messageType=" + messageType +
                '}';
    }
}
