/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.demo.kafka.json.consumer.dto;


public class MessageKey {
    private String productId;


    public String getProductId() {
        return productId;
    }

    public MessageKey setProductId(String productId) {
        this.productId = productId;
        return MessageKey.this;
    }

    public static MessageKey newBuilder() {
        return new MessageKey();
    }

    @Override
    public String toString() {
        return "MessageKey{" +
                "productId='" + productId + '\'' +
                '}';
    }
}
